### ISSUE TITLE
crear carpetas y archivos principales del proyecto

### ISSUE THREAD

**Issue by Facundo-Arana** [Facundo-Arana/Trabajo-Practico-Especial-TIO#5]
Añadir al repositorio el trabajo practico de web 1.

**Comment by gabrielquatt** [comment]
cargada la carpeta paginas, css, javascript, imagenes y creados archivos principales del proyecto (index.html, novedades.html, inicio.html, juegos.html) cargadas imagenes y edicion de informe.
